### ISSUE TITLE
ustreamer service configuration

### ISSUE THREAD

**Issue by tabshadel** [mdevaev/mdevaev#1]
hello
I have ustreamer runing on a debian 11 machine and have connected two USB caneras to the machine.
I installed ustreamer by typing: 
apt update
apt install ustreamer
it installed fine (v3.16). My two cameras ade vedices video1 and video3. They are both working fine when I run the comand like:
ustreamer --device=/dev/video3 --format=JPEG --host=192.168.1.160 -p 8081 -r 1920x1080
I can open my browser and use this URL: http://192,168.160:8081/?action=stream and view a nice stream (of myself ) and very clear and no lag  whatsover in the image.
unfortunately, ustreamer takes over the session with this output:
-- INFO  [93.822      main] -- Using internal blank placeholder
-- INFO  [93.823      main] -- Listening HTTP on [192.168.1.160]:8081
-- INFO  [93.824    stream] -- Using V4L2 device: /dev/video3
-- INFO  [93.824    stream] -- Using desired FPS: 0
-- INFO  [93.824      http] -- Starting HTTP eventloop ...
================================================================================
-- INFO  [93.984    stream] -- Device fd=8 opened
-- INFO  [93.985    stream] -- Using input channel: 0
-- INFO  [94.000    stream] -- Using resolution: 1920x1080
-- INFO  [94.001    stream] -- Using pixelformat: JPEG
-- INFO  [94.016    stream] -- Using HW FPS: 0 -> 30 (coerced)
-- ERROR [94.016    stream] -- Device does not support setting of HW encoding quality parameters
-- INFO  [94.016    stream] -- Using IO method: MMAP
-- INFO  [94.030    stream] -- Requested 5 device buffers, got 5
-- INFO  [94.047    stream] -- Capturing started
-- INFO  [94.047    stream] -- Switching to HW encoder: the input is (M)JPEG ...
-- INFO  [94.048    stream] -- Using JPEG quality: encoder default
-- INFO  [94.048    stream] -- Creating pool JPEG with 1 workers ...
-- INFO  [94.048    stream] -- Capturing ...
-- INFO  [106.811      http] -- HTTP: Registered client: [192.168.1.104]:52077, id=a5257f48-4c42-4649-98f8-8814185c8df9; clients now: 1

and the only way to get back to my prompt is with <CTRL> C at which time the streaming obviously stops!
So I then followed the instructions of haow to make ustreamer run as a service and here is my confiuration:
[Unit]
Description=uStreamer service
After=network.target
[Service]
Environment="SCRIPT_ARGS=%I"
User=ustreamer
ExecStart=/usr/bin/ustreamer --process-name-prefix ustreamer-3 --log-level 0 --device /dev/video3 --device-timeout=8  --quality 100 --host=192.168.1.160 --p=1081 --resolution 1920x1080 --desired-fps=29  --static /var/www/html/ustreamer-3/
[Install]
WantedBy=multi-user.target
I enabled and restarted the service and checked its status with this output:
systemctl status ustreamer@3.service
● ustreamer@3.service - uStreamer service
     Loaded: loaded (/etc/systemd/system/ustreamer@.service; disabled; vendor preset: enabled)
     Active: active (running) since Sun 2023-07-30 13:15:34 MDT; 20s ago
   Main PID: 1995 (main)
      Tasks: 7 (limit: 775)
     Memory: 6.1M
        CPU: 6.740s
     CGroup: /system.slice/system-ustreamer.slice/ustreamer@3.service
             └─1995 ustreamer-3: /usr/bin/ustreamer --process-name-prefix ustreamer-3 --log-level 0 --device /dev/video3 --device-timeout=8 --qualit>

Jul 30 13:15:34 armbian ustreamer[1995]: -- INFO  [1393.927    stream] -- Using input channel: 0
Jul 30 13:15:34 armbian ustreamer[1995]: -- INFO  [1393.943    stream] -- Using resolution: 1920x1080
Jul 30 13:15:34 armbian ustreamer[1995]: -- INFO  [1393.943    stream] -- Using pixelformat: YUYV
Jul 30 13:15:34 armbian ustreamer[1995]: -- INFO  [1393.959    stream] -- Using HW FPS: 29 -> 5 (coerced)
Jul 30 13:15:34 armbian ustreamer[1995]: -- INFO  [1393.959    stream] -- Using IO method: MMAP
Jul 30 13:15:34 armbian ustreamer[1995]: -- INFO  [1393.973    stream] -- Requested 5 device buffers, got 5
Jul 30 13:15:34 armbian ustreamer[1995]: -- INFO  [1393.992    stream] -- Capturing started
Jul 30 13:15:34 armbian ustreamer[1995]: -- INFO  [1393.992    stream] -- Using JPEG quality: 100%
Jul 30 13:15:34 armbian ustreamer[1995]: -- INFO  [1393.993    stream] -- Creating pool JPEG with 4 workers ...
Jul 30 13:15:34 armbian ustreamer[1995]: -- INFO  [1393.994    stream] -- Capturing ...

but cannot reach the stream from my web browser when I use this URL: http://192.168.1.160:8083/?action=stream
and get the error :Not Found
Can you help me figure out whats going on?
Thank you. It's a great piece of software.

**Comment by tabshadel** [comment]
update:
I also tried this configuration:
[Unit]
Description=uStreamer service
After=network.target
[Service]
Environment="SCRIPT_ARGS=%I"
User=ustreamer
ExecStart=/usr/bin/ustreamer --process-name-prefix ustreamer-%I --log-level 0 --device /dev/video%I --device-timeout=8  --quality 100 --resolution 1920x1080 --desired-fps=29 --host=192.168.1.160 --port=808%I --static /var/www/html/ustreamer-%I/
[Install]
WantedBy=multi-user.target
and used "3" as the value for I with the same problem

**Comment by mdevaev** [comment]
Please format your message and move it to https://github.com/pikvm/ustreamer, this is my personal page.
